#ifndef PROBABILITIES_H
#define PROBABILITIES_H

#define MONACO_CRASH_CHANCE 20
#define MONACO_AW_LOOT_CHANCE 50
#define MONACO_HP_LOOT_CHANCE 40
#define MONACO_WG_LOOT_CHANCE 20
#define MONACO_MOD_WEAR_CHANCE 20

#define SPA_RAIN_FUEL_CHANCE 25
#define SPA_AW_LOOT_CHANCE 35
#define SPA_HP_LOOT_CHANCE 40
#define SPA_WG_LOOT_CHANCE 25
#define SPA_MOD_WEAR_CHANCE 25

#define MONZA_ITEM_LOSS_CHANCE 10
#define MONZA_AW_LOOT_CHANCE 25
#define MONZA_HP_LOOT_CHANCE 30
#define MONZA_WG_LOOT_CHANCE 12
#define MONZA_MOD_WEAR_CHANCE 15

#endif // PROBABILITIES_H
